### ISSUE TITLE
Remove DateInput default hint 'For example, 12 11 2007'

### ISSUE THREAD

**Issue by happy-devs** [daniel-ac-martin/NotGovUK#647]
Hi @daniel-ac-martin, I'm using this library on a project and really appreciate the scope of its components; just noticed that the `DateInput` component includes a hint as a default and thought it should be flagged for removal in case some others are caught out.

Thanks again for the work on this!

**Comment by daniel-ac-martin** [comment]
Hi @happy-devs.
Just to be clear, are you saying that you are seeing a hint even when you don't provide one to the component?

**Comment by daniel-ac-martin** [comment]
Oh, sorry just spotted it.
Yes, that's a bug. Not sure how I managed that.

Thanks for raising it!

**Comment by daniel-ac-martin** [comment]
Hi @happy-devs.

I've been thinking about this one. I think that I put in that default hint because all of the GDS examples have hints and the DateInput probably _needs_ a hint in order to make it clear to users, how they should use it. e.g. That they should enter a number for the month rather than say 'Jan'.

Can you tell me any more about your use case where you don't want a hint?

Also, can you get rid of the hint by passing an empty string (`hint=""`)?

**Comment by happy-devs** [comment]
Hi @daniel-ac-martin, sure can; this is more of personal opinion on my end to prevent any wrong hints getting through. thanks for clarifying!
